version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          {
            spring.datasource.url=jdbc:mysql://$DATASOURCE_URL/$DATASOURCE_DB
            spring.datasource.username=$DATASOURCE_DB_USERNAME
            spring.datasource.password=$DATASOURCE_DB_PASSWORD
            spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
          }
      - image: cimg/mysql:8.0
        environment:
          MYSQL_USER: $DATASOURCE_DB_USERNAME
          MYSQL_PASSWORD: $DATASOURCE_DB_PASSWORD
          MYSQL_DATABASE: $DATASOURCE_DB
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db
          command: dockerize -wait tcp://$DATASOURCE_URL -timeout 1m
      - run: chmod +x ./gradlew
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      # run tests!
      - run: ./gradlew test

workflows:
  version: 2
  checkout-build-test:
    jobs:
      - build-and-test:
          context: forecast-database
