version: 2
jobs:
  build-and-test:
    docker:
      - image: cimg/mysql:8.0
        environment:
          MYSQL_USER: $DATASOURCE_DB_USERNAME
          MYSQL_PASSWORD: $DATASOURCE_DB_PASSWORD
          MYSQL_DATABASE: $DATASOURCE_DB
      - image: cimg/openjdk:17.0.4-browsers
        environment:
          {
            spring.datasource.url=jdbc:mysql://$DATASOURCE_URL/$DATASOURCE_DB
            spring.datasource.username=$DATASOURCE_DB_USERNAME
            spring.datasource.password=$DATASOURCE_DB_PASSWORD
            spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
          }
    working_directory: ~/project
    steps:
      - checkout
      - run: java --version
      - run: chmod +x gradlew
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
      # run tests!
      - run: ./gradlew test

workflows:
  version: 2
  checkout-build-test:
    jobs:
      - build-and-test:
          context: forecast-database
