version: 2.1
orbs:
  gradle: circleci/gradle@3.0.0
executors:
  jdk-docker-image:
    docker:
      - image: cimg/openjdk:18.0.2
    environment:
      {
        spring.datasource.url=jdbc:mysql://$DATASOURCE_URL/$DATASOURCE_DB
        spring.datasource.username=$DATASOURCE_DB_USERNAME
        spring.datasource.password=$DATASOURCE_DB_PASSWORD
        spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
      }
  docker-publisher:
    environment:
      IMAGE_NAME: milkamt/springboot-forecast
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
#  build-app:
#    docker:
#      - image: circleci/openjdk:11-jdk
#    working_directory: ~/project
#    steps:
#      - checkout
#      - run: chmod +x ./gradlew
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "build.gradle" }}
#            - v1-dependencies-
#      - run: ./gradlew dependencies
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: v1-dependencies-{{ checksum "build.gradle" }}
#      - run: ./gradlew test --stacktrace
  build-docker:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest-docker:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          executor: jdk-docker-image
          context: forecast-database
#     - build-docker:
#          requires:
#            - build-app
#          filters:
#            branches:
#              only: main
#      - publish-latest-docker:
#          context: docker
#          requires:
#            - build-docker
#          filters:
#            branches:
#              only: main